# Use the official Nginx image
FROM nginx:alpine

# Install required packages: Node.js, npm, and PostgreSQL server
RUN apk add --no-cache nodejs npm postgresql

# Initialize PostgreSQL database
RUN mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql && \
    su postgres -c "initdb -D /var/lib/postgresql/data"

# Set the working directory
WORKDIR /app

COPY package.json package-lock.json ./

# Replace the default Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy an entrypoint script to handle database initialization
COPY entrypoint.dev.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN npm install -g turbo

EXPOSE 80

# Use the entrypoint script to start services
ENTRYPOINT ["/entrypoint.sh"]
